### ISSUE TITLE
Suggestion: Insert link in AsciiDoc format when the document itself is in AsciiDoc

### ISSUE THREAD

**Issue by earshinov** [usernamehw/vscode-url-title#1]
Hello @usernamehw, thank you for this handy extension! What do you think about supporting AsciiDoc in addition to Markdown? I believe Markdown could remain the default since it's much more widespread, but I myself frequently use AsciiDoc for documentation and other purposes. It would be great if the extension recognized AsciiDoc and inserted links in the appropriate format, so that I wouldn't have to reformat them manually. If you like the idea, I'd be happy to take it on and submit a PR.

**Comment by usernamehw** [comment]
Would it require adding some external dependencies (detecting/parsing text) or
simply using **`https://asciidoctor.org[Asciidoctor]`** format when file extension is `.adoc` or `.asciidoc`?

**Comment by earshinov** [comment]
The latter, only using a different format

**Comment by usernamehw** [comment]
You can try it out in the `0.2.0` version.

**Comment by earshinov** [comment]
Works as intended. Thank you very much!

**Comment by earshinov** [comment]
Hello @usernamehw! Sorry for bothering you again, but I hit on another idea. What do you think of supporting HTML as well, that is insert an HTML link (`<a href="$url">$urlTitle</a>`) when the document being edited is HTML, similarly to what you did for AsciiDoc?

(Please let me know if you'd like to me to file a separate issue. I decided not to do this right away to avoid spamming.)

_Update_: Filed #2
